---
resource_types:
- name: test-container
  type: docker-image
  source:
    repository: python
    tag: 2-alpine3.8 

resources:
- name: source-code
  type: git
  check_every: 3m
  source:
    uri: https://github.com/nigel-mellish/concourse-tut-task
    branch: master
    paths: 
      - "src/*"

jobs:
- name: run-unit-tests
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: run-tests
    file: concourse-tut-task/ci/tasks/sample-task.yml
