---
resource_types:
- name: source-code
  type: docker-image
  source:
    repository: python
    tag: 2-alpine3.8 
  
- name: source-code
  type: git
  check_every: 3m
  source:
    uri: https://github.com/nigel-mellish/concourse-tut-task
    branch: master
    paths: 
      - "src/*"