---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/nigel-mellish/concourse-tut-task.git
    branch: master

jobs:
- name: do-stuff
  public: true
  plan:
  - get: source-code
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: python }
      inputs: 
      - name: source-code
      run:
        user: root
        path: source-code/ci/scripts/sample_script.sh
  - task: setup-build-arguments
    file: source-code/ci/tasks/sample-task.yml